function [Jh,J_Jhdq] = Symb_Jh(x1,x2,x3,x4,x5,x6,q1Switch,h_alpha1,h_alpha2,h_alpha3,h_alpha4,h_alpha5,h_alpha6,h_alpha7,h_alpha8,h_alpha9,h_alpha10,h_alpha11,h_alpha12)
%SYMB_JH
%    [JH,J_JHDQ] = SYMB_JH(X1,X2,X3,X4,X5,X6,Q1SWITCH,H_ALPHA1,H_ALPHA2,H_ALPHA3,H_ALPHA4,H_ALPHA5,H_ALPHA6,H_ALPHA7,H_ALPHA8,H_ALPHA9,H_ALPHA10,H_ALPHA11,H_ALPHA12)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    17-May-2019 17:21:10

t2 = 1.0./q1Switch;
t5 = (t2.*x1)./2.0;
t3 = t5-1.0./2.0;
t4 = t3.^2;
t6 = t4.^2;
t7 = t5+1.0./2.0;
t8 = t7.^2;
t9 = t8.^2;
t10 = t2.*x1.*(5.0./2.0);
t11 = t10+5.0./2.0;
Jh = reshape([h_alpha1.*t2.*t6.*(5.0./2.0)-h_alpha2.*t2.*t6.*(5.0./2.0)+h_alpha5.*t2.*t9.*(5.0./2.0)-h_alpha6.*t2.*t9.*(5.0./2.0)+h_alpha3.*t2.*t4.*t8.*1.5e1-h_alpha4.*t2.*t4.*t8.*1.5e1+h_alpha3.*t2.*t3.*t4.*t7.*1.0e1-h_alpha2.*t2.*t3.*t4.*t11.*2.0-h_alpha4.*t2.*t3.*t7.*t8.*1.0e1+h_alpha5.*t2.*t3.*t7.*t8.*1.0e1,h_alpha7.*t2.*t6.*(5.0./2.0)-h_alpha8.*t2.*t6.*(5.0./2.0)+h_alpha11.*t2.*t9.*(5.0./2.0)-h_alpha12.*t2.*t9.*(5.0./2.0)+h_alpha9.*t2.*t4.*t8.*1.5e1-h_alpha10.*t2.*t4.*t8.*1.5e1+h_alpha9.*t2.*t3.*t4.*t7.*1.0e1-h_alpha8.*t2.*t3.*t4.*t11.*2.0-h_alpha10.*t2.*t3.*t7.*t8.*1.0e1+h_alpha11.*t2.*t3.*t7.*t8.*1.0e1,0.0,1.0,1.0,0.0],[2,3]);
if nargout > 1
    t12 = 1.0./q1Switch.^2;
    t13 = x4.^2;
    J_Jhdq = [t13.*(h_alpha1.*t3.*t4.*t12.*5.0-h_alpha2.*t3.*t4.*t12.*1.0e1+h_alpha3.*t3.*t4.*t12.*5.0+h_alpha3.*t3.*t8.*t12.*1.5e1+h_alpha3.*t4.*t7.*t12.*3.0e1-h_alpha4.*t3.*t8.*t12.*3.0e1-h_alpha4.*t4.*t7.*t12.*1.5e1+h_alpha5.*t3.*t8.*t12.*1.5e1-h_alpha2.*t4.*t11.*t12.*3.0-h_alpha4.*t7.*t8.*t12.*5.0+h_alpha5.*t7.*t8.*t12.*1.0e1-h_alpha6.*t7.*t8.*t12.*5.0);t13.*(h_alpha7.*t3.*t4.*t12.*5.0-h_alpha8.*t3.*t4.*t12.*1.0e1+h_alpha9.*t3.*t4.*t12.*5.0+h_alpha9.*t3.*t8.*t12.*1.5e1+h_alpha9.*t4.*t7.*t12.*3.0e1-h_alpha10.*t3.*t8.*t12.*3.0e1-h_alpha10.*t4.*t7.*t12.*1.5e1+h_alpha11.*t3.*t8.*t12.*1.5e1-h_alpha8.*t4.*t11.*t12.*3.0-h_alpha10.*t7.*t8.*t12.*5.0+h_alpha11.*t7.*t8.*t12.*1.0e1-h_alpha12.*t7.*t8.*t12.*5.0)];
end
